using Bogus;
using DevBeast.Mcp.Server.Models;

namespace DevBeast.Mcp.Server.Services;

public interface IFixtureGeneratorService
{
    Task<string> GenerateAsync(string tableName, int count = 10, CancellationToken cancellationToken = default);
}

public sealed class FixtureGeneratorService(IDatabaseService databaseService) : IFixtureGeneratorService
{
    public async Task<string> GenerateAsync(string tableName, int count = 10, CancellationToken cancellationToken = default)
    {
        if (count is < 1 or > 500)
        {
            throw new ArgumentOutOfRangeException(nameof(count), "Count must be between 1 and 500.");
        }

        var schema = await databaseService.GetTableSchemaAsync(tableName, cancellationToken);
        var faker = new Faker();
        var entries = new List<Dictionary<string, object?>>();

        for (var i = 0; i < count; i++)
        {
            var entry = new Dictionary<string, object?>();
            foreach (var column in schema.Columns)
            {
                if (column.IsPrimaryKey && column.Name is "Id" or "_id")
                {
                    entry[column.Name] = Guid.NewGuid();
                    continue;
                }

                entry[column.Name] = GenerateValue(faker, column);
            }

            entries.Add(entry);
        }

        var code = GenerateCSharpSeedCode(tableName, entries);
        return code;
    }

    private static object? GenerateValue(Faker faker, ColumnInfo column)
    {
        var type = column.DataType.ToLowerInvariant();

        if (type.Contains("guid") || type.Contains("objectid")) return Guid.NewGuid();
        if (type.Contains("int") || type.Contains("int32")) return faker.Random.Int(1, 10000);
        if (type.Contains("long") || type.Contains("int64")) return faker.Random.Long(1, 100000);
        if (type.Contains("decimal") || type.Contains("double") || type.Contains("float") || type.Contains("number")) return faker.Random.Decimal(1, 9999);
        if (type.Contains("bool") || type.Contains("boolean")) return faker.Random.Bool();
        if (type.Contains("datetime") || type.Contains("date")) return faker.Date.RecentOffset(30);
        if (column.Name.Contains("email", StringComparison.OrdinalIgnoreCase)) return faker.Internet.Email();
        if (column.Name.Contains("name", StringComparison.OrdinalIgnoreCase)) return faker.Commerce.ProductName();
        if (column.Name.Contains("sku", StringComparison.OrdinalIgnoreCase)) return $"SKU-{faker.Random.Int(100, 999)}";
        if (column.Name.Contains("price", StringComparison.OrdinalIgnoreCase) || column.Name.Contains("amount", StringComparison.OrdinalIgnoreCase)) return faker.Random.Decimal(10, 5000);

        return faker.Lorem.Word();
    }

    private static string GenerateCSharpSeedCode(string tableName, IReadOnlyList<Dictionary<string, object?>> entries)
    {
        var className = $"{Sanitize(tableName)}SeedData";
        var lines = new List<string>
        {
            "// Auto-generated by DevBeast MCP — generate_test_fixtures",
            "using Bogus;",
            "",
            $"public static class {className}",
            "{",
            $"    public static IReadOnlyList<{Sanitize(tableName)}Entity> Generate(int count = {entries.Count})",
            "    {",
            $"        var faker = new Faker<{Sanitize(tableName)}Entity>()",
        };

        foreach (var entry in entries.Take(3))
        {
            foreach (var kvp in entry)
            {
                lines.Add($"            .RuleFor(x => x.{Sanitize(kvp.Key)}, _ => {FormatValue(kvp.Value)})");
            }
        }

        lines.Add("            ;");
        lines.Add("");
        lines.Add("        return faker.Generate(count);");
        lines.Add("    }");
        lines.Add("}");
        lines.Add("");
        lines.Add($"public sealed record {Sanitize(tableName)}Entity({string.Join(", ", entries.FirstOrDefault()?.Keys.Select(k => $"{MapType(entries.First()[k])} {Sanitize(k)}") ?? [])});");

        return string.Join(Environment.NewLine, lines);
    }

    private static string Sanitize(string name) =>
        string.Concat(name.Split(['_', '.'], StringSplitOptions.RemoveEmptyEntries)
            .Select(s => char.ToUpper(s[0]) + s[1..]));

    private static string MapType(object? value) => value switch
    {
        Guid => "Guid",
        int => "int",
        long => "long",
        decimal => "decimal",
        double => "double",
        bool => "bool",
        DateTimeOffset => "DateTimeOffset",
        _ => "string"
    };

    private static string FormatValue(object? value) => value switch
    {
        null => "null",
        string s => $"\"{s}\"",
        bool b => b ? "true" : "false",
        Guid g => $"Guid.Parse(\"{g}\")",
        DateTimeOffset dto => $"DateTimeOffset.Parse(\"{dto:O}\")",
        _ => value.ToString() ?? "null"
    };
}
